### ISSUE TITLE
Can't find the config dir in aws lambda environment

### ISSUE THREAD

**Issue by rohit-gandhe** [sitture/env-config#30]
### Prerequisites

Put an `x` in all the boxes that apply

* [x] Are you running the latest version?
* [x] Did you perform a cursory search?
* [x] Have you a detailed log to share?

For more information, see the `CONTRIBUTING` guide.

### Description

When I deploy in aws lambda, I get a config dir not found error. Locally, the code works fine.

**Expected behavior:** [What you expected to happen]
The library tries to locate the config dir in /var/task/config because it's the root in the lambda environment, but can't find it because it seems like the project root is not the same as lambda root

**Actual behavior:** [What actually happened]
The lib finds the dir

**Versions:** [What version of JDK/JRE and other tools are using]
Java 8

This is more like a plea for guidance than an issue. Has anybody deployed on lambda? If so, what did you set you CONFIG_DIR environment variable to?

Relevant log:
[2021-04-30 07:54:45.374] <5e08bf1a-dee9-41a2-90fb-3f1503d7107c>
                DEBUG c.g.s.e.c.ConfigLoader - config.dir set to 'config'

ERROR c.a.a.BaseFunction - Error: 1fa9abe4-779e-42b9-8b21-69dcefe29642
com.github.sitture.env.config.ConfigException: '/var/task/config/DEV' does not exist or not a valid config directory!
	at com.github.sitture.env.config.ConfigLoader.getConfigFiles(ConfigLoader.java:85)
	at com.github.sitture.env.config.ConfigLoader.loadFileConfigurations(ConfigLoader.java:144)
	at com.github.sitture.env.config.ConfigLoader.loadConfigurations(ConfigLoader.java:123)
	at com.github.sitture.env.config.EnvConfig.<init>(EnvConfig.java:21)
	at com.github.sitture.env.config.EnvConfig.getConfig(EnvConfig.java:32)
	at com.github.sitture.env.config.EnvConfig.get(EnvConfig.java:132)

**Comment by rohit-gandhe** [comment]
Worked after I moved the config dir to java/main/resources directory and set the System.setProperty("config.dir", "config");
